### ISSUE TITLE
Background Events that share timeframe overlap their titles

### ISSUE THREAD

**Issue by wanwindwalker** [seanlowe/obsidian-timelines#27] opened 2024-03-21 23:10 UTC
Would it be possible display them on different heights at the appropriate zoom levels

**Comment by seanlowe** [comment] 2024-10-04 19:55
This is a somewhat of a dupe of #23 (or at least it'll touch the same code), moving it to live under that one.

**Closed by seanlowe** 2024-10-04 19:56 UTC
Labels: bug/confirmed, styling
